export const FREE_LOADING = "FREE_LOADING";

export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const RESETPASSWORD_LOADING = "RESETPASSWORD_LOADING";
export const RESETPASSWORD_ERROR = "RESETPASSWORD_ERROR";
export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";

export const RESETUSERNAME_LOADING = "RESETUSERNAME_LOADING";
export const RESETUSERNAME_ERROR = "RESETUSERNAME_ERROR";
export const RESETUSERNAME_SUCCESS = "RESETUSERNAME_SUCCESS";

export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
export const ADD_USER_STATUS = "ADD_USER_STATUS";
